version: '2'

volumes:
  data:

services:
  tf:
    build: .
    volumes:
      - ./notebooks:/notebooks
      - ./logs:/logs
      - ./data:/data
      - ./:/code
    ports:
      - "8888:8888"
    
  # tb:
  #   build: .
  #   volumes:
  #     - ./notebooks:/notebooks
  #     - ./data:/data
  #     - ./logs:/logs
  #     - ./:/code
  #   ports:
  #     - "6006:6006"
  #   command: bash -c "tensorboard --logdir /logs --host 0.0.0.0"
